### ISSUE TITLE
Offchain signing is not working

### ISSUE THREAD

**Issue by anxolin** [TP-Lab/tp-ios#2]
## Description
Offchain signing using eip-712 is not working. The app display nicely the information to sign, but it gives an error when you try to do so. 

Android App just fixed the signing issue, but IOS app still don't have the fix. See https://github.com/TP-Lab/tp-android/issues/16 for context.

Offchain transaction is required for some Dapps like http://cowswap.exchange

## How to repoduce
1. Go to https://pr674--gpswapui.review.gnosisdev.com
2. Connect your wallet. You can use Rinkeby, Mainnet or xDAI
3. Select any token pair you have in your balance. If you want to use ETH you will need to wrap it first (can be done in the app)
4. Approve the token
5. Try to Swap

## Screenshot
![image](https://user-images.githubusercontent.com/2352112/122229243-deab3a80-ceb8-11eb-94e3-d9d16b56f56a.png)

**Comment by chendatony31** [comment]
Try to update, the newest version for the App Store should be 1.5.9  @anxolin

**Comment by anxolin** [comment]
I updated it and It works! Good job adding offchain tx also for Wallet Connect :)
